#specifies the version og the compose file format
name: mapappproject

#defines the contiainers that will be started as part of the docker
#compose instance. Each service represent a container and includes various config options
services:
  #web:
  #  build: ./Client
  #  ports: 
  #    - "80:80"
#    depends_on:
  #    - server

  server:
    build: /
    ports:
      - "5000:5000"
    # env_file:
    #  - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network1

  db:
    image: postgres:16
    container_name: mydb
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network1

  keydb:
    image: eqalpha/keydb:latest
    container_name: mykeydb
    ports:
      - "6000:6000"
    volumes:
      - keydb_data:/data
    networks:
      - network1

volumes:
  postgres_data:
  keydb_data:

networks:
  network1:
    driver: bridge